### ISSUE TITLE
fails with no error message when site is down

### ISSUE THREAD

**Issue by ericbjones** [rexpress/magaret#6]
currently https://regular.express/ is down.  It looks like the domain renewal did not get taken care of or something.  Because of this, the tool does not work at all.  Sad day.

**Comment by nghoanghiep** [comment]
still not working

**Comment by Prev** [comment]
I checked the problem of the client, but the domain is not main cause of the error.

I think it's a problem because [Docker](https://www.docker.com) is not installed. We have not correctly handled this, so the error message does not seem to be working.

So download Docker on [here](https://www.docker.com/get-docker) (or docker machine) and try again it.

`Sharing` feature still has a problem because of the domain and the server expiration, and it will be restored later.

Thanks.

**Comment by nghoanghiep** [comment]
wow you're my savior. thank you very very much, that fixed the problem
